FROM node:12.13

# Create app directory and use it as the working directory
RUN mkdir -p /srv/app/fr-shohin-admin-client

copy . /srv/app/fr-shohin-admin-client

WORKDIR /svr/app/fr-shohin-admin-client