version: '3'

services:
##########################
# Setun client Container #
##########################
  client:
    build: ./client
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports: 
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes: 
      - ./client/src:/srv/app/client/src
      - ./client/public:/srv/app/client/public
    command: npm run start